version: "3.7"

services:
  garoh:
    image: registry.gitlab.com/cyberchuvash/garohbot:1.1.3
    env_file:
      - .env
    restart: unless-stopped
    networks:
      garohnet:

networks:
  garohnet:
